### ISSUE TITLE
On Label Click open popup like in Storybook

### ISSUE THREAD

**Issue by HekMe** [appbaseio-apps/reactivemaps-starter#1]
Hey,

in: [Playground](https://opensource.appbase.io/playground/?selectedKind=Map%20Components%2FReactiveMap&selectedStory=Basic&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybooks%2Fstorybook-addon-knobs), there's popup when you click on label(magnitude).
Is there source online, or are there any docs for this feature?
![image](https://user-images.githubusercontent.com/8376384/45031963-baa44480-b050-11e8-8bae-14d3f0a40a9e.png)

Thanks

**Comment by metagrover** [comment]
[Check docs here](https://opensource.appbase.io/reactive-manual/map-components/reactivemap.html) - `onPopoverClick`
